sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- echo "This design module has no tests"
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: QB/jJmyrPU2HO+gKxZPV0zIaPM6GKu1JMUiEcyLS4TNevBfcjwAyxThqwQP3ZAeUzzs66VgMqDVKXQbsZmCKzd8tcr7Rk1kDEj3saI6OrZzpYeQcc65TvAulZzlBS2a0j3POMJrvxkaN6h1TBQXDYx4194CRNoQn32M5W0rzsYVSuIugXhRSg8+BZNaeC7pmSN7ED54oFNHT5ptWOvcMawBNeM7OTx3AcKa+cN2x3JucfSaIHPNIWnnrv/FbtOwLB1LGwz+XKCpJ6gGuIblzop7mGaKW8In19Xi0cbjSkciybGu4tM9GwduliXs1V7BTDeR5eMAASLooZIGMGFzolKB2/7nbQZbGpgKXPLEmchvI2ZwclKkuQnRRhGmRqOuq4KVvVYnx2di5F1mlfN09p+Dgyf15E687ZRIyeHYgHh+Vgo4/M0YtB2TRSlMIh7ijKgAx+e4ZxOmFdws6E+HYsZ5n346SpbSCKrRaPH5moIwt7LlX+5g2fHnwBVminUzUzKlDhGQtyfQpQww2oqsoqO3ylYUh3HUPSjgJMXgfqXLAeJV8r+rqKANhXxj9n5JV1dAZkpUQCnRvE5/lkAaUm/2gI7CNnWcrhuzo4I14FTOq6JlBRyNDk6Kk0mjadOwNRWCXauTQ9Mr6r9FMphqudh0ian9ZyGSxxBCWmQPZ+Dw=
  - secure: A/b4DwWFXYWWCj4RQzwz/CIu/sOiJUyLxtY9LtcRiLrUtb691eQCud7a/rjg35aTs7LjddO4/wpoMQUHkAqXFYJ72F6/gbZluG29UwaCFmStj/0eiB89kDryx9ZcTTnUhfkT3334gsLty0x9FPy4p3jsfW0ipmvswZdOeciDsWc+uRC/0wqjxisr4nuXMcUENSzzGxNZMsNoLH1CYR6gcdKFpxjctxLjukqUkg54q1msqCP3tE8akP0w+ecNxzpnoUl2pLphL6VbXsor/9Ybta4cWG/k0QS2+Y/JcXhCMJKqv1X2UU7g8Q0XUCquVGLHtTPKv/PERXGkVSs0iMsm6PhDCkrLA1wxxP0bfIxlsT6UJpyh91ZRT581V8U7VsiV34MqkDCm/XLbZrUoHlmdIGmJNtOPUIsHgE9Ej5uuqRQHwKw4z9yxO+9ZtEdxjwwrUIMhsno1WYdxQksEdUqqgHxixamArtW19btjUtoR2xgVAg0ZmRNYi8HS7tuDhkFU0W8tVeVKbceiZHL7axkwk5XaIpPvTdHV6Z16m8JNKNwj365tcQlXrFFcIY59HIa0vKEaQ6/XylB+Ag8wsu84MKQGG2hxW/YTQiODIE6MV48aaahJ65UO3Xlg34zCpgpsDLR7CsO3T45g4acM0SkFFa/WrF+PpcnRyf9Ifg5MawU=
  - secure: Ls4s4I3eA5gUZ4P0UrxTHGCcssJv7G/PxP/sjcN5xodKHbIFlHjn3ptMT7PRh9b+9yeMmDKiMxFd4MtBEeNlep3pIXdNNJzn5ql1IjjBZpNccDQA5Wb92rVmWmpeXcWuvTpZDJFQXzt9oawHjVDrV7PoRpow2qT+E3A48jlDCIe1SA63c4nVzbMM4Cmu39s8abCnt1kawf76YIjDxyaFuHYAuY/5kjY1nV2JJDXFvKQVlvenUXxykdI0w8v99xraNVVyECMIMiKKvA5D2yNel5Exf7K7PL1bHVH23T8jMUwYbTot2e01nbJgNLPngQFIabYDocyrRANORgb06cv2OGPsVHBgjDWd7mfZPDUg4m+xgq6uugcRDOkzgqwK08ZcCR5wJn/9UxEHgczR5JSubuwoWFy+2LrbJEYmBoSRFgC5I8Sg6dpVIViWBmRHd/Gya8fHuXSfmjWmk+IeTcZWTg/amywTb2cTdranQEZw/Mst6wZ1EzBX/ZfimqT4n4iXCuRqQiN76q8qf4SG6jqtAOu3iuUFH3utRCsI/dB8qpJaUtPcwqicsyfdw67iCOHQEsAUnJXbe+gaJIfusxRvNYZCHq1oElvgDpzbT/xIjVht5H8gb8v7PL1E+Pd2I9rZPYv7Ce8anHLp5Yr/DyzCol/MCCjJlvkanVqhbnkUHCE=
